export const LABELS = {
  APP_TITLE: 'Easy Assistant',
  EMAIL: 'Email Address',
  PASSWORD: 'Password',
  LOGIN: 'Login',
  LOGOUT: 'Logout',
  SIGNUP: 'Sign Up',
  DASHBOARD: 'Dashboard',
  APPOINTMENTS: 'Appointments',
  CONVERSATIONS: 'Conversations',
  STAFF: 'Staff',
  SERVICES: 'Services',
  AVAILABILITY: 'Availability',
  CHANNELS: 'Channels',
  MARKETING: 'Marketing',
  AI_SETTINGS: 'AI Settings',
  BILLING: 'Billing',
  ANALYTICS: 'Analytics',
  SUPPORT: 'Support',
  SETTINGS: 'Settings',
  PRIVACY: 'Privacy Policy',
  TERMS: 'Terms of Service',
  ONBOARDING: 'Onboarding',
  SEARCH_PLACEHOLDER: 'Search...',
  REMEMBER_ME: 'Remember me',
  FORGOT_PASSWORD: 'Forgot password?',
  DONT_HAVE_ACCOUNT: "Don't have an account?",
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',
} as const;

export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  APPOINTMENTS: '/appointments',
  CONVERSATIONS: '/conversations',
  STAFF: '/staff',
  SERVICES: '/services',
  AVAILABILITY: '/availability',
  CHANNELS: '/channels',
  MARKETING: '/marketing',
  AI_SETTINGS: '/ai-settings',
  BILLING: '/billing',
  ANALYTICS: '/analytics',
  SUPPORT: '/support',
  SETTINGS: '/settings',
  PRIVACY: '/privacy',
  TERMS: '/terms',
} as const;
