export const LABELS = {
  APP_TITLE: 'Easy Assistant',
  EMAIL: 'Email Address',
  PASSWORD: 'Password',
  LOGIN: 'Login',
  LOGOUT: 'Logout',
  SIGNUP: 'Sign Up',
  DASHBOARD: 'Dashboard',
  APPOINTMENTS: 'Appointments',
  CONVERSATIONS: 'Conversations',
  STAFF: 'Staff',
  SERVICES: 'Services',
  AVAILABILITY: 'Availability',
  CHANNELS: 'WhatsApp',
  AI_SETTINGS: 'Assistant',
  SETTINGS: 'Account',
  PRIVACY: 'Privacy Policy',
  TERMS: 'Terms of Service',
  REMEMBER_ME: 'Remember me',
  DONT_HAVE_ACCOUNT: "Don't have an account?",
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',
} as const;

export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  DASHBOARD: '/dashboard',
  APPOINTMENTS: '/appointments',
  CONVERSATIONS: '/conversations',
  STAFF: '/staff',
  SERVICES: '/services',
  AVAILABILITY: '/availability',
  CHANNELS: '/channels',
  AI_SETTINGS: '/ai-settings',
  SETTINGS: '/settings',
  PRIVACY: '/privacy',
  TERMS: '/terms',
} as const;
